# Experiment 5: Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers
## Name: Sufiyan Mehsanewala
## Class: SE AIML 
## Roll no: 44

In [97]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import pandas as pd

In [98]:
data = load_breast_cancer()

X = data.data
y = data.target

print("Classes: ", data.target_names)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=44)

Classes:  ['malignant' 'benign']

In [99]:
# print(data.data.shape)
df = pd.DataFrame(data.data, columns=data.feature_names)
df.shape

(569, 30)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [101]:
df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [102]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [103]:
df.tail()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [104]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

## A: Training and Test Accuracy (Learning Behaviour of ML Model)

### Logistic Regression

In [105]:
lr = LogisticRegression(max_iter = 5000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_lr))
pred_lr_train = lr.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_lr_train))

Logistic TestAccuracy: 0.9707602339181286
Logistic TrainAccuracy: 0.9623115577889447

### Decision Tree Classifier

In [106]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred_dt = dt.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_dt))
pred_dt_train = dt.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_dt_train))

Logistic TestAccuracy: 0.935672514619883
Logistic TrainAccuracy: 1.0

### KNN

In [107]:
kn = KNeighborsClassifier()
kn.fit(X_train, y_train)
pred_kn = kn.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_kn))
pred_kn_train = kn.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_kn_train))

Logistic TestAccuracy: 0.9590643274853801
Logistic TrainAccuracy: 0.9346733668341709

### Naive Bayes

In [108]:
nb = GaussianNB()
nb.fit(X_train, y_train)
pred_nb = nb.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_nb))
pred_nb_train = nb.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_nb_train))

Logistic TestAccuracy: 0.9415204678362573
Logistic TrainAccuracy: 0.9371859296482412

### Neural Network

In [109]:
nn = MLPClassifier(max_iter = 2000)
nn.fit(X_train, y_train)
pred_nn = nn.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_nn))
pred_nn_train = nn.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_nn_train))

Logistic TestAccuracy: 0.9590643274853801
Logistic TrainAccuracy: 0.9271356783919598

## B: Classification Performance Metrics (Threshold-based Evaluation)

### Logistic Regression

In [110]:
precision_lr = precision_score(y_test, pred_lr)
recall_lr = recall_score(y_test, pred_lr)
f1_lr = f1_score(y_test, pred_lr)
roc_auc_lr = roc_auc_score(y_test, pred_lr)
print("Logistic Regression Metrics:")
print("Precision:", precision_lr)
print("Recall:", recall_lr)
print("F1 Score:", f1_lr)
print("ROC AUC Score:", roc_auc_lr)

Logistic Regression Metrics:
Precision: 0.963963963963964
Recall: 0.9907407407407407
F1 Score: 0.9771689497716894
ROC AUC Score: 0.9636243386243386

### Decision Tree Classifier

In [111]:
precision_dt = precision_score(y_test, pred_dt)
recall_dt = recall_score(y_test, pred_dt)
f1_dt = f1_score(y_test, pred_dt)
roc_auc_dt = roc_auc_score(y_test, pred_dt)
print("Decision Tree Metrics:")
print("Precision:", precision_lr)
print("Recall:", recall_lr)
print("F1 Score:", f1_lr)
print("ROC AUC Score:", roc_auc_dt)

Decision Tree Metrics:
Precision: 0.963963963963964
Recall: 0.9907407407407407
F1 Score: 0.9771689497716894
ROC AUC Score: 0.9358465608465608

### KNN

In [112]:
precision_knn = precision_score(y_test, pred_kn)
recall_knn = recall_score(y_test, pred_kn)
f1_knn = f1_score(y_test, pred_kn)
roc_auc_knn = roc_auc_score(y_test, pred_kn)
print("K Nearest Neighbor Metrics:")
print("Precision:", precision_knn)
print("Recall:", recall_knn)
print("F1 Score:", f1_knn)
print("ROC AUC Score:", roc_auc_knn)

K Nearest Neighbor Metrics:
Precision: 0.9719626168224299
Recall: 0.9629629629629629
F1 Score: 0.9674418604651163
ROC AUC Score: 0.9576719576719575

### Naive Bayes

In [113]:
precision_nb = precision_score(y_test, pred_nb)
recall_nb = recall_score(y_test, pred_nb)
f1_nb = f1_score(y_test, pred_nb)
roc_auc_nb = roc_auc_score(y_test, pred_nb)
print("Naive Bayes Metrics:")
print("Precision:", precision_nb)
print("Recall:", recall_nb)
print("F1 Score:", f1_nb)
print("ROC AUC Score:", roc_auc_nb)

Naive Bayes Metrics:
Precision: 0.9537037037037037
Recall: 0.9537037037037037
F1 Score: 0.9537037037037037
ROC AUC Score: 0.9371693121693122

### Neural Network

In [114]:
precision_nn = precision_score(y_test, pred_nn)
recall_nn = recall_score(y_test, pred_nn)
f1_nn = f1_score(y_test, pred_nn)
roc_auc_nn = roc_auc_score(y_test, pred_nn)
print("Neural Network Metrics:")
print("Precision:", precision_nn)
print("Recall:", recall_nn)
print("F1 Score:", f1_nn)
print("ROC AUC Score:", roc_auc_nn)

Neural Network Metrics:
Precision: 0.9809523809523809
Recall: 0.9537037037037037
F1 Score: 0.9671361502347418
ROC AUC Score: 0.9609788359788359

### C: Confusion Matrix and Error Analysis

### Logistic Regression

In [115]:
cm_lr = confusion_matrix(y_test, pred_lr)
print("\nDecision Tree Confusion Matrix: ")
print(cm_lr)
TN2, FP2, FN2, TP2 = cm_lr.ravel()
type1_lr = FP2 / (FP2 + TN2)
type2_lr = FN2 / (FN2 + TP2)

print("FP (type-1): ", FP2)
print("FP (type-2): ", FN2)
print("type-1 Error Rate in %: ", type1_lr*100)
print("type-2 Error Rate in %: ", type2_lr*100)

Decision Tree Confusion Matrix:
[[ 59   4]
 [  1 107]]
FP (type-1):  4
FP (type-2):  1
type-1 Error Rate in %:  6.349206349206349
type-2 Error Rate in %:  0.9259259259259258

### Decision Tree Classifier

In [116]:
cm_dt = confusion_matrix(y_test, pred_dt)
print("\nDecision Tree Confusion Matrix: ")
print(cm_dt)
TN2, FP2, FN2, TP2 = cm_dt.ravel()
type1_dt = FP2 / (FP2 + TN2)
type2_dt = FN2 / (FN2 + TP2)

print("FP (type-1): ", FP2)
print("FP (type-2): ", FN2)
print("type-1 Error Rate in %: ", type1_dt*100)
print("type-2 Error Rate in %: ", type2_dt*100)

Decision Tree Confusion Matrix:
[[ 59   4]
 [  7 101]]
FP (type-1):  4
FP (type-2):  7
type-1 Error Rate in %:  6.349206349206349
type-2 Error Rate in %:  6.481481481481481

### KNN

In [117]:
cm_kn = confusion_matrix(y_test, pred_kn)
print("\nDecision Tree Confusion Matrix: ")
print(cm_kn)
TN2, FP2, FN2, TP2 = cm_kn.ravel()
type1_kn = FP2 / (FP2 + TN2)
type2_kn = FN2 / (FN2 + TP2)

print("FP (type-1): ", FP2)
print("FP (type-2): ", FN2)
print("type-1 Error Rate in %: ", type1_kn*100)
print("type-2 Error Rate in %: ", type2_kn*100)

Decision Tree Confusion Matrix:
[[ 60   3]
 [  4 104]]
FP (type-1):  3
FP (type-2):  4
type-1 Error Rate in %:  4.761904761904762
type-2 Error Rate in %:  3.7037037037037033

### Naive Bayes

In [118]:
cm_nb = confusion_matrix(y_test, pred_nb)
print("\nDecision Tree Confusion Matrix: ")
print(cm_nb)
TN2, FP2, FN2, TP2 = cm_nb.ravel()
type1_nb = FP2 / (FP2 + TN2)
type2_nb = FN2 / (FN2 + TP2)

print("FP (type-1): ", FP2)
print("FP (type-2): ", FN2)
print("type-1 Error Rate in %: ", type1_nb*100)
print("type-2 Error Rate in %: ", type2_nb*100)

Decision Tree Confusion Matrix:
[[ 58   5]
 [  5 103]]
FP (type-1):  5
FP (type-2):  5
type-1 Error Rate in %:  7.936507936507936
type-2 Error Rate in %:  4.62962962962963

### Neural Network

In [119]:
cm_nn = confusion_matrix(y_test, pred_nn)
print("\nDecision Tree Confusion Matrix: ")
print(cm_nn)
TN2, FP2, FN2, TP2 = cm_nn.ravel()
type1_nn = FP2 / (FP2 + TN2)
type2_nn = FN2 / (FN2 + TP2)

print("FP (type-1): ", FP2)
print("FP (type-2): ", FN2)
print("type-1 Error Rate in %: ", type1_nn*100)
print("type-2 Error Rate in %: ", type2_nn*100)

Decision Tree Confusion Matrix:
[[ 61   2]
 [  5 103]]
FP (type-1):  2
FP (type-2):  5
type-1 Error Rate in %:  3.1746031746031744
type-2 Error Rate in %:  4.62962962962963